"""Add text column to questions

Revision ID: f3c0ad2e621f
Revises: c798f20b53c5
Create Date: 2025-12-15 21:31:44.002495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3c0ad2e621f'
down_revision: Union[str, Sequence[str], None] = 'c798f20b53c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'text')
    # ### end Alembic commands ###
